# Generated by Django 3.0.4 on 2020-06-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texttolatex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convert',
            old_name='item',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='convert',
            name='identifier',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
